:- dynamic(lex_adj/4). 

lex_adj(adventurous,K,person(K,adventurous),person).
lex_adj(aggressive,K,person(K,aggressive),person).
lex_adj(agreeable,K,person(K,agreeable),person).
lex_adj(alert,K,person(K,alert),person).
lex_adj(alive,K,person(K,alive),person).
lex_adj(amused,K,person(K,amused),person).
lex_adj(angry,K,person(K,angry),person).
lex_adj(annoyed,K,person(K,annoyed),person).
lex_adj(annoying,K,person(K,annoying),person).
lex_adj(anxious,K,person(K,anxious),person).
lex_adj(arrogant,K,person(K,arrogant),person).
lex_adj(ashamed,K,person(K,ashamed),person).
lex_adj(attractive,K,person(K,attractive),person).
lex_adj(average,K,person(K,average),person).
lex_adj(awful,K,person(K,awful),person).
lex_adj(bad,K,person(K,bad),person).
lex_adj(beautiful,K,person(K,beautiful),person).
lex_adj(better,K,person(K,better),person).
lex_adj(bewildered,K,person(K,bewildered),person).
lex_adj(black,K,person(K,black),person).
lex_adj(bloody,K,person(K,bloody),person).
lex_adj(blue,K,person(K,blue),person).
lex_adj(blue-eyed,K,person(K,blue-eyed),person).
lex_adj(blushing,K,person(K,blushing),person).
lex_adj(bored,K,person(K,bored),person).
lex_adj(brainy,K,person(K,brainy),person).
lex_adj(brave,K,person(K,brave),person).
lex_adj(breakable,K,person(K,breakable),person).
lex_adj(bright,K,person(K,bright),person).
lex_adj(busy,K,person(K,busy),person).
lex_adj(calm,K,person(K,calm),person).
lex_adj(careful,K,person(K,careful),person).
lex_adj(cautious,K,person(K,cautious),person).
lex_adj(charming,K,person(K,charming),person).
lex_adj(cheerful,K,person(K,cheerful),person).
lex_adj(clean,K,person(K,clean),person).
lex_adj(clear,K,person(K,clear),person).
lex_adj(clever,K,person(K,clever),person).
lex_adj(cloudy,K,person(K,cloudy),person).
lex_adj(clumsy,K,person(K,clumsy),person).
lex_adj(colorful,K,person(K,colorful),person).
lex_adj(combative,K,person(K,combative),person).
lex_adj(comfortable,K,person(K,comfortable),person).
lex_adj(concerned,K,person(K,concerned),person).
lex_adj(condemned,K,person(K,condemned),person).
lex_adj(confused,K,person(K,confused),person).
lex_adj(cooperative,K,person(K,cooperative),person).
lex_adj(courageous,K,person(K,courageous),person).
lex_adj(crazy,K,person(K,crazy),person).
lex_adj(creepy,K,person(K,creepy),person).
lex_adj(crowded,K,person(K,crowded),person).
lex_adj(cruel,K,person(K,cruel),person).
lex_adj(curious,K,person(K,curious),person).
lex_adj(cute,K,person(K,cute),person).
lex_adj(dangerous,K,person(K,dangerous),person).
lex_adj(dark,K,person(K,dark),person).
lex_adj(dead,K,person(K,dead),person).
lex_adj(defeated,K,person(K,defeated),person).
lex_adj(defiant,K,person(K,defiant),person).
lex_adj(delightful,K,person(K,delightful),person).
lex_adj(depressed,K,person(K,depressed),person).
lex_adj(determined,K,person(K,determined),person).
lex_adj(different,K,person(K,different),person).
lex_adj(difficult,K,person(K,difficult),person).
lex_adj(disgusted,K,person(K,disgusted),person).
lex_adj(distinct,K,person(K,distinct),person).
lex_adj(disturbed,K,person(K,disturbed),person).
lex_adj(dizzy,K,person(K,dizzy),person).
lex_adj(doubtful,K,person(K,doubtful),person).
lex_adj(drab,K,person(K,drab),person).
lex_adj(dull,K,person(K,dull),person).
lex_adj(eager,K,person(K,eager),person).
lex_adj(easy,K,person(K,easy),person).
lex_adj(elated,K,person(K,elated),person).
lex_adj(elegant,K,person(K,elegant),person).
lex_adj(embarrassed,K,person(K,embarrassed),person).
lex_adj(enchanting,K,person(K,enchanting),person).
lex_adj(encouraging,K,person(K,encouraging),person).
lex_adj(energetic,K,person(K,energetic),person).
lex_adj(enthusiastic,K,person(K,enthusiastic),person).
lex_adj(envious,K,person(K,envious),person).
lex_adj(evil,K,person(K,evil),person).
lex_adj(excited,K,person(K,excited),person).
lex_adj(expensive,K,person(K,expensive),person).
lex_adj(exuberant,K,person(K,exuberant),person).
lex_adj(f,K,person(K,f),person).
lex_adj(fair,K,person(K,fair),person).
lex_adj(faithful,K,person(K,faithful),person).
lex_adj(famous,K,person(K,famous),person).
lex_adj(fancy,K,person(K,fancy),person).
lex_adj(fantastic,K,person(K,fantastic),person).
lex_adj(fierce,K,person(K,fierce),person).
lex_adj(filthy,K,person(K,filthy),person).
lex_adj(fine,K,person(K,fine),person).
lex_adj(foolish,K,person(K,foolish),person).
lex_adj(fragile,K,person(K,fragile),person).
lex_adj(frail,K,person(K,frail),person).
lex_adj(frantic,K,person(K,frantic),person).
lex_adj(friendly,K,person(K,friendly),person).
lex_adj(frightened,K,person(K,frightened),person).
lex_adj(funny,K,person(K,funny),person).
lex_adj(gentle,K,person(K,gentle),person).
lex_adj(gifted,K,person(K,gifted),person).
lex_adj(glamorous,K,person(K,glamorous),person).
lex_adj(gleaming,K,person(K,gleaming),person).
lex_adj(glorious,K,person(K,glorious),person).
lex_adj(good,K,person(K,good),person).
lex_adj(gorgeous,K,person(K,gorgeous),person).
lex_adj(graceful,K,person(K,graceful),person).
lex_adj(grieving,K,person(K,grieving),person).
lex_adj(grotesque,K,person(K,grotesque),person).
lex_adj(grumpy,K,person(K,grumpy),person).
lex_adj(handsome,K,person(K,handsome),person).
lex_adj(happy,K,person(K,happy),person).
lex_adj(healthy,K,person(K,healthy),person).
lex_adj(helpful,K,person(K,helpful),person).
lex_adj(helpless,K,person(K,helpless),person).
lex_adj(hilarious,K,person(K,hilarious),person).
lex_adj(homeless,K,person(K,homeless),person).
lex_adj(homely,K,person(K,homely),person).
lex_adj(horrible,K,person(K,horrible),person).
lex_adj(hungry,K,person(K,hungry),person).
lex_adj(hurt,K,person(K,hurt),person).
lex_adj(ill,K,person(K,ill),person).
lex_adj(important,K,person(K,important),person).
lex_adj(impossible,K,person(K,impossible),person).
lex_adj(inexpensive,K,person(K,inexpensive),person).
lex_adj(innocent,K,person(K,innocent),person).
lex_adj(inquisitive,K,person(K,inquisitive),person).
lex_adj(itchy,K,person(K,itchy),person).
lex_adj(jealous,K,person(K,jealous),person).
lex_adj(jittery,K,person(K,jittery),person).
lex_adj(jolly,K,person(K,jolly),person).
lex_adj(joyous,K,person(K,joyous),person).
lex_adj(kind,K,person(K,kind),person).
lex_adj(lazy,K,person(K,lazy),person).
lex_adj(light,K,person(K,light),person).
lex_adj(lively,K,person(K,lively),person).
lex_adj(lonely,K,person(K,lonely),person).
lex_adj(long,K,person(K,long),person).
lex_adj(lovely,K,person(K,lovely),person).
lex_adj(lucky,K,person(K,lucky),person).
lex_adj(magificent,K,person(K,magificent),person).
lex_adj(misty,K,person(K,misty),person).
lex_adj(modern,K,person(K,modern),person).
lex_adj(motionless,K,person(K,motionless),person).
lex_adj(muddy,K,person(K,muddy),person).
lex_adj(mushy,K,person(K,mushy),person).
lex_adj(mysterious,K,person(K,mysterious),person).
lex_adj(nasty,K,person(K,nasty),person).
lex_adj(naughty,K,person(K,naughty),person).
lex_adj(nervous,K,person(K,nervous),person).
lex_adj(nice,K,person(K,nice),person).
lex_adj(nutty,K,person(K,nutty),person).
lex_adj(obedient,K,person(K,obedient),person).
lex_adj(obnoxious,K,person(K,obnoxious),person).
lex_adj(odd,K,person(K,odd),person).
lex_adj(old-fashioned,K,person(K,old-fashioned),person).
lex_adj(open,K,person(K,open),person).
lex_adj(outrageous,K,person(K,outrageous),person).
lex_adj(outstanding,K,person(K,outstanding),person).
lex_adj(panicky,K,person(K,panicky),person).
lex_adj(perfect,K,person(K,perfect),person).
lex_adj(plain,K,person(K,plain),person).
lex_adj(pleasant,K,person(K,pleasant),person).
lex_adj(poised,K,person(K,poised),person).
lex_adj(poor,K,person(K,poor),person).
lex_adj(powerful,K,person(K,powerful),person).
lex_adj(precious,K,person(K,precious),person).
lex_adj(prickly,K,person(K,prickly),person).
lex_adj(proud,K,person(K,proud),person).
lex_adj(puzzled,K,person(K,puzzled),person).
lex_adj(quant,K,person(K,quant),person).
lex_adj(real,K,person(K,real),person).
lex_adj(relieved,K,person(K,relieved),person).
lex_adj(repulsive,K,person(K,repulsive),person).
lex_adj(rich,K,person(K,rich),person).
lex_adj(scary,K,person(K,scary),person).
lex_adj(selfish,K,person(K,selfish),person).
lex_adj(shiny,K,person(K,shiny),person).
lex_adj(shy,K,person(K,shy),person).
lex_adj(silly,K,person(K,silly),person).
lex_adj(sleepy,K,person(K,sleepy),person).
lex_adj(smiling,K,person(K,smiling),person).
lex_adj(smoggy,K,person(K,smoggy),person).
lex_adj(sore,K,person(K,sore),person).
lex_adj(sparkling,K,person(K,sparkling),person).
lex_adj(splendid,K,person(K,splendid),person).
lex_adj(spotless,K,person(K,spotless),person).
lex_adj(stormy,K,person(K,stormy),person).
lex_adj(strange,K,person(K,strange),person).
lex_adj(stupid,K,person(K,stupid),person).
lex_adj(successful,K,person(K,successful),person).
lex_adj(super,K,person(K,super),person).
lex_adj(talented,K,person(K,talented),person).
lex_adj(tame,K,person(K,tame),person).
lex_adj(tender,K,person(K,tender),person).
lex_adj(tense,K,person(K,tense),person).
lex_adj(terrible,K,person(K,terrible),person).
lex_adj(tasty,K,person(K,tasty),person).
lex_adj(thankful,K,person(K,thankful),person).
lex_adj(thoughtful,K,person(K,thoughtful),person).
lex_adj(thoughtless,K,person(K,thoughtless),person).
lex_adj(tired,K,person(K,tired),person).
lex_adj(tough,K,person(K,tough),person).
lex_adj(troubled,K,person(K,troubled),person).
lex_adj(ugliest,K,person(K,ugliest),person).
lex_adj(ugly,K,person(K,ugly),person).
lex_adj(uninterested,K,person(K,uninterested),person).
lex_adj(unsightly,K,person(K,unsightly),person).
lex_adj(unusual,K,person(K,unusual),person).
lex_adj(upset,K,person(K,upset),person).
lex_adj(uptight,K,person(K,uptight),person).
lex_adj(vast,K,person(K,vast),person).
lex_adj(victorious,K,person(K,victorious),person).
lex_adj(vivacious,K,person(K,vivacious),person).
lex_adj(wandering,K,person(K,wandering),person).
lex_adj(weary,K,person(K,weary),person).
lex_adj(wicked,K,person(K,wicked),person).
lex_adj(wide-eyed,K,person(K,wide-eyed),person).
lex_adj(wild,K,person(K,wild),person).
lex_adj(witty,K,person(K,witty),person).
lex_adj(worrisome,K,person(K,worrisome),person).
lex_adj(worried,K,person(K,worried),person).
lex_adj(wrong,K,person(K,wrong),person).
lex_adj(zany,K,person(K,zany),person).
lex_adj(zealous,K,person(K,zealous),person).
lex_adj(romantic,K,film(K,romantic),film).
lex_adj(dramatic,K,film(K,dramatic),film).
lex_adj(action,K,film(K,action),film).
lex_adj(rock,K,music(K,rock),music).
lex_adj(alternative,K,music(K,alternative),music).
lex_adj(pop,K,music(K,pop),music).
lex_adj(classical,K,music(K,classical),music).
