:- dynamic(lex_proper_names/2).
lex_proper_names(clara,person).
lex_proper_names(michele,person).
lex_proper_names(maria,person).
lex_proper_names(marco,person).
lex_proper_names(gianni,person).
lex_proper_names(francesco,person).
lex_proper_names(luigi,person).
lex_proper_names(antonella,person).
lex_proper_names(marcello,person).
lex_proper_names(francesca,person).
lex_proper_names(nicola,person).
lex_proper_names(davide,person).
lex_proper_names(daniele,person).
lex_proper_names(raffaella,person).
lex_proper_names(andrea,person).
lex_proper_names(prof_smith,professor).
lex_proper_names(prof_white,professor).
lex_proper_names(prof_red,professor).
lex_proper_names(prof_black,professor).
lex_proper_names(bari,location).
lex_proper_names(milano,location).
lex_proper_names(roma,location).
lex_proper_names(londra,location).
lex_proper_names(napoli,location).
lex_proper_names(parigi,location).
lex_proper_names(bob,animal).
lex_proper_names(rex,animal).
lex_proper_names(fido,animal).
lex_proper_names(monday,day).
lex_proper_names(tuesday,day).
lex_proper_names(wedsnday,day).
lex_proper_names(thursday,day).
lex_proper_names(friday,day).
lex_proper_names(saturday,day).
lex_proper_names(sunday,day).
lex_proper_names(english,subject).
lex_proper_names(italian,subject).
lex_proper_names(math,subject).
lex_proper_names(history,subject).
lex_proper_names(latin,subject).
lex_proper_names(water,drink).
